# Generated by Django 4.1.4 on 2022-12-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_job_type_alter_user_net_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='income',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
