# Generated by Django 4.1.4 on 2022-12-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.FloatField()),
                ('lend', models.IntegerField(default=0)),
                ('borrow', models.IntegerField(default=0)),
            ],
        ),
    ]
