# Generated by Django 4.1.4 on 2022-12-31 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='budget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.budget'),
            preserve_default=False,
        ),
    ]
