# Generated by Django 4.1.4 on 2022-12-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mas_trans',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
