# Generated by Django 4.1.4 on 2023-01-01 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_mas_trans_type_groups_trans'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups_trans',
            name='grp_trans_id',
            field=models.OneToOneField(default=61, on_delete=django.db.models.deletion.CASCADE, to='transaction.mas_trans'),
            preserve_default=False,
        ),
    ]
